### ISSUE TITLE
Just checking in... is hush-house still ongoing...?

### ISSUE THREAD

**Issue by aegershman** [concourse/hush-house#65]
Hey! It's been a while since the last commit to master in this repo, and it's still on 5.4.1 even though the chart for 5.5.x is out.

Just wanted to check, is `hush-house` still being used as an internal testbed at Pivotal? If it's moved to a private repo to prevent randos like myself from commenting on it, that's completely understandable, I just wanted to check in to see what was up.

OR, if nothing is different, and the reason nothing has changed is simply because things are hummingly along smoothly & no one has decided to go to 5.5.x yet, that's completely understandable too. Just wanted to see either way.

Thanks!

**Comment by cirocosta** [comment]
heey, it actually is!

The lack of a bump there was actually a mistake 😅 you can see how not being "gitops" since the inception was a bad idea (we have an issue for it though) - it currently runs on 5.5.0 (`{"version":"5.5.0","worker_version":"2.2","external_url":"https://hush-house.pivotal.io","cluster_name":"hush-house"}`) 

At the same time, yeah, it's been quite smooth.

That I remember, here are the known issues in it:

- https://github.com/concourse/hush-house/issues/22 (will be improved once we get a more recent kernel on GKE - i.e., in the very next version)
- https://github.com/concourse/concourse/issues/3127 got patched for Pivotal's stemcells
- https://github.com/concourse/concourse/issues/4467 sometimes makes us get a worker here / there with "max containers" when a workload misbehaves (e.g., "kubernetes in docker" types of workloads - see reproducible: https://github.com/concourse/concourse/issues/4477) 

Aside from that though, it's been pretty much just maintaining it and onboarding new teams 😁

**Comment by aegershman** [comment]
Nah s'all good, was just making sure I didn't miss anything lol. Thank you, apologies didn't mean to be pushy or spammy 👍
